version: '2'

services:

  identityserver:
    build: .
    ports:
      - "8443:8443"
    volumes:
      - .:/go/src/github.com/itsyouonline/identityserver
    links:
      - mongo
    entrypoint: ["sh", "-c", "go generate && go build && ./identityserver -d -c mongo:27017"]

  mongo:
    image: mongo
    ports:
      - "27017:27017"
